version: '3'
services:
  ui:
    container_name: ui_dev
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - ./ui:/usr/create-dapp/ui
      - /usr/create-dapp/ui/node_modules
    working_dir: /usr/create-dapp/ui
  tests:
    container_name: ui_tests_dev
    build:
      context: ./ui
      dockerfile: Dockerfile.test
    volumes:
      - ./ui:/usr/create-dapp/ui
      - /usr/create-dapp/ui/node_modules
    working_dir: /usr/create-dapp/ui