version: '3'
services:
  ui:
    container_name: ui_prod
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
    ports: 
      - "1337:1337"
    volumes:
      - /usr/create-dapp/ui/node_modules
    working_dir: /usr/create-dapp/ui