version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    command: "ganache-cli"
    ports:
      - "8545:8545"
  truffle:
    container_name: truffle
    working_dir: /usr/create-dapp/ethereum
    ports:
    - "8080:8080"
    build:
      context: ./ethereum
      dockerfile: Dockerfile.build
    depends_on:
      - "ganache"
    stdin_open: true
    tty: true
    volumes:
    - ./ethereum:/usr/create-dapp/ethereum
    - /usr/create-dapp/ethereum/node_modules
    command: |
      sh -c "truffle migrate --reset"
  ui:
    container_name: ui_dev
    working_dir: /usr/create-dapp/ui
    ports:
    - "1337:3000"
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    links:
      - ganache
    depends_on:
      - "ganache"
      - "truffle"
    volumes:
      - ./ui:/usr/create-dapp/ui
      - ./ethereum/config:/usr/create-dapp/ui/src/ethereum
      - /usr/create-dapp/ui/node_modules
    command: |
      sh -c "npm run dev"
  api:
    container_name: api_dev
    working_dir: /usr/create-dapp/api
    ports:
    - "1117:4000"
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    links:
      - ganache
    depends_on:
      - "ganache"
      - "truffle"
    volumes:
    - ./api:/usr/create-dapp/api
    - ./ethereum/config:/usr/create-dapp/api/ethereum
    - /usr/create-dapp/api/node_modules
    command: |
      sh -c "npm run dev-docker"