version: '3'
services:
  ui:
    container_name: ui
    build:
      ## specifies where the source files are for the service, in this casae this directory
      context: ./ui
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /usr/create-dapp/ui/node_modules
      - ./ui:/usr/create-dapp/ui/