version: '3'
services:
  ui_tests:
    container_name: ui_tests
    build:
      context: ./ui
      dockerfile: Dockerfile.test
    volumes:
      - ./ui:/usr/create-dapp/ui
      - /usr/create-dapp/ui/node_modules
    working_dir: /usr/create-dapp/ui