FROM node:alpine as builder
WORKDIR /usr/create-dapp/ethereum
COPY package.json .
COPY . .

RUN apk add git
RUN apk add --virtual .gyp \
        python \
        make \
        g++ \
    && npm install \
    && cd node_modules/scrypt-for-humans/node_modules/scrypt \
    && node-gyp configure build \
    && apk del .gyp

## necessary to install truffle globally 
RUN mkdir -p /root/.config/configstore
RUN chmod g+rwx /root /root/.config /root/.config/configstore

RUN npm install -g truffle