FROM alpine-node:11 as builder
WORKDIR /usr/create-dapp/ethereum
COPY package.json .
COPY . .

RUN apk add git
RUN apk add --virtual .gyp \
        python \
        make \
        g++ 

RUN npm install

## necessary to install truffle globally 
RUN mkdir -p /root/.config/configstore
RUN chmod g+rwx /root /root/.config /root/.config/configstore

RUN npm install -g truffle