FROM node:alpine
WORKDIR /usr/create-dapp/truffle
COPY package.json .

RUN apk add --no-cache git
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm install \
    && apk del .gyp

## necessary to install truffle globally 
RUN mkdir -p /root/.config/configstore
RUN chmod g+rwx /root /root/.config /root/.config/configstore

RUN npm install -g truffle

CMD ["truffle", "develop"]

RUN test