FROM node:alpine as builder

WORKDIR /usr/create-dapp/ui

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /usr/create-dapp/ui/build /usr/share/nginx/html

WORKDIR /usr/create-dapp/ui

RUN npm install -g serve
