FROM node:alpine
WORKDIR /usr/create-dapp/api
COPY package.json .
COPY . .
RUN apk add git
RUN apk add --virtual .gyp \
        python \
        make \
        g++ 
RUN npm install
CMD ["npm", "run", "prod"]